name: CI Check
on: [pull_request, workflow_dispatch]
jobs:
  clean-and-test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        python-version: ['3.9', '3.13']
      fail-fast: false
    steps:
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
    - name: Getting repository
      uses: actions/checkout@v4

    - name: Install dependencies and package
      env:
        BLIS_ARCH: generic
      run: |
        python -m pip install --upgrade pip
        pip install spacy --no-binary blis
        pip install -e .
    - name: Install pytest
      run: |
        pip install pytest pytest-cov

    - name: Execute PyTest
      run: python -m pytest -svv --cov=mailcom --cov-report=xml:mailcom/coverage_re/coverage.xml

    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v4.0.1
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        directory: ./mailcom/coverage_re/

